<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
        <None Remove="appsettings*.json"/>
        <Content Include="..\OlympusVMS\appsettings.json">
            <Link>appsettings.json</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\OlympusVMS\appsettings.Development.json">
            <Link>appsettings.Development.json</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\OlympusVMS\appsettings.Staging.json">
            <Link>appsettings.Staging.json</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OlympusVMS.Services\OlympusVMS.Services.csproj" />
      <ProjectReference Include="..\OlympusVMS.Utils\OlympusVMS.Utils.csproj" />
    </ItemGroup>

</Project>
